---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Магазин должен быть SPA-приложением
  - Список товаров выводится постранично
  - На странице карточки товара нужно выводить информацию о товаре - название, фото, рейтинг, количество, цена со скидкой и без нее.
  - В каталоге товаров нужно выводить информацию о товарах - название, фото, рейтинг, количество, цена со скидкой и без нее.
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера
  - При добавлении товара в корзину, пользователь должен иметь возможность вводить количество товара
  - На странице корзины должна подсчитываться общая сумма заказа
  - На всех страницах каталога товаров должны быть блоки навигации и фильтров
  - На странице корзины должен быть блок навигации
  - Пользователь должен иметь возможность сбросить все фильтры поиска товаров, чтобы не перезагружать страницу
